# Generated by dconf-nix
{ lib, ... }:

{
  dconf.settings = {
    "org/gnome/TextEditor" = {
      style-scheme = "stylix";
    };
    "org/gnome/desktop/app-folders" = {
      folder-children = [ "System" "Utilities" "YaST" "Pardus" ];
    };
    "org/gnome/desktop/app-folders/folders/Pardus" = {
      categories = [ "X-Pardus-Apps" ];
      name = "X-Pardus-Apps.directory";
      translate = true;
    };
    "org/gnome/desktop/app-folders/folders/System" = {
      apps = [ "org.gnome.baobab.desktop" "org.gnome.DiskUtility.desktop" "org.gnome.Logs.desktop" "org.gnome.tweaks.desktop" ];
      name = "X-GNOME-Shell-System.directory";
      translate = true;
    };
    "org/gnome/desktop/app-folders/folders/Utilities" = {
      apps = [ "org.gnome.Decibels.desktop" "org.gnome.Connections.desktop" "org.gnome.font-viewer.desktop" "org.gnome.Loupe.desktop" "org.gnome.seahorse.Application.desktop" "org.gnome.Evince.desktop" "org.gnome.FileRoller.desktop" ];
      name = "X-GNOME-Shell-Utilities.directory";
      translate = true;
    };
    "org/gnome/desktop/app-folders/folders/YaST" = {
      categories = [ "X-SuSE-YaST" ];
      name = "suse-yast.directory";
      translate = true;
    };
    "org/gnome/desktop/input-sources" = {
      sources = [ "[xkb us]" "[xkb ru]" ];
      xkb-options = [ "terminate:ctrl_alt_bksp" ];
    };
    "org/gnome/desktop/interface" = {
      accent-color = "slate";
      color-scheme = "prefer-dark";
      enable-animations = true;
      toolkit-accessibility = false;
    };
    "org/gnome/desktop/screensaver" = {
      lock-delay = lib.hm.gvariant.mkUint32 0;
      lock-enabled = true;
    };
    "org/gnome/desktop/session" = {
      idle-delay = lib.hm.gvariant.mkUint32 600;
    };
    "org/gnome/desktop/wm/preferences" = {
      button-layout = "appmenu:minimize,maximize,close";
      num-workspaces = 3;
    };
    "org/gnome/mutter" = {
      edge-tiling = true;
      experimental-features = [ "scale-monitor-framebuffer" ];
    };
    "org/gnome/nautilus/compression" = {
      default-compression-format = "tar.xz";
    };
    "org/gnome/nautilus/preferences" = {
      default-folder-viewer = "icon-view";
      search-filter-time-type = "last_modified";
    };
    "org/gnome/settings-daemon/plugins/color" = {
      night-light-schedule-automatic = false;
    };
    "org/gnome/settings-daemon/plugins/power" = {
      sleep-inactive-ac-timeout = 0;
      sleep-inactive-ac-type = "nothing";
      sleep-inactive-battery-timeout = 0;
      sleep-inactive-battery-type = "nothing";
    };
    "org/gnome/shell" = {
      disable-user-extensions = false;
      disabled-extensions = [ "ding@rastersoft.com" "color-picker@tuberry" ];
      enabled-extensions = [ "AlphabeticalAppGrid@stuarthayhurst" "appindicatorsupport@rgcjonas.gmail.com" "blur-my-shell@aunetx" "dash-in-panel@fthx" "gsconnect@andyholmes.github.io" "solaar-extension@sidevesh" "user-theme@gnome-shell-extensions.gcampax.github.com" "Vitals@CoreCoding.com" "caffeine@patapon.info" "pop-shell@system76.com" "undecorate@sun.wxg@gmail.com" "logomenu@aryan_k" "just-perfection-desktop@just-perfection" "auto-accent-colour@Wartybix" ];
      favorite-apps = [ "zen.desktop" "org.gnome.Nautilus.desktop" "org.telegram.desktop.desktop" "com.mitchellh.ghostty.desktop" "dev.zed.Zed.desktop" ];
      last-selected-power-profile = "performance";
    };
    "org/gnome/shell/extensions/Logo-menu" = {
      hide-forcequit = true;
      hide-icon-shadow = false;
      hide-softwarecentre = true;
      menu-button-extensions-app = "org.gnome.Extensions.desktop";
      menu-button-icon-click-type = 2;
      menu-button-icon-image = 23;
      menu-button-icon-size = 24;
      menu-button-software-center = "";
      menu-button-system-monitor = "missioncenter";
      menu-button-terminal = "ghostty";
      show-activities-button = false;
      show-lockscreen = true;
      show-power-options = true;
      symbolic-icon = true;
      use-custom-icon = false;
    };
    "org/gnome/shell/extensions/alphabetical-app-grid" = {
      folder-order-position = "start";
    };
    "org/gnome/shell/extensions/appindicator" = {
      icon-brightness = 0;
      icon-contrast = 0;
      icon-opacity = 240;
      icon-saturation = 0;
      icon-size = 0;
      legacy-tray-enabled = true;
      tray-pos = "right";
    };
    "org/gnome/shell/extensions/auto-accent-colour" = {
      disable-cache = false;
      hide-indicator = true;
      highlight-mode = true;
    };
    "org/gnome/shell/extensions/blur-my-shell" = {
      hacks-level = 1;
    };
    "org/gnome/shell/extensions/blur-my-shell/appfolder" = {
      brightness = 1;
      sigma = 85;
    };
    "org/gnome/shell/extensions/blur-my-shell/applications" = {
      blacklist = [ "Plank" "com.desktop.ding" "Conky" ".gamescope-wrapped" "steam_app_*" ".virt-manager-wrapped" ];
      blur = false;
      dynamic-opacity = false;
      enable-all = true;
      opacity = 230;
      sigma = 85;
    };
    "org/gnome/shell/extensions/blur-my-shell/coverflow-alt-tab" = {
      pipeline = "pipeline_default";
    };
    "org/gnome/shell/extensions/blur-my-shell/dash-to-dock" = {
      blur = false;
      brightness = 1;
      override-background = true;
      pipeline = "pipeline_default_rounded";
      sigma = 85;
      static-blur = false;
      style-dash-to-dock = 0;
      unblur-in-overview = true;
    };
    "org/gnome/shell/extensions/blur-my-shell/dash-to-panel" = {
      blur-original-panel = false;
    };
    "org/gnome/shell/extensions/blur-my-shell/hidetopbar" = {
      compatibility = false;
    };
    "org/gnome/shell/extensions/blur-my-shell/lockscreen" = {
      pipeline = "pipeline_default";
    };
    "org/gnome/shell/extensions/blur-my-shell/overview" = {
      pipeline = "pipeline_default";
    };
    "org/gnome/shell/extensions/blur-my-shell/panel" = {
      brightness = 1;
      override-background = true;
      pipeline = "pipeline_default";
      sigma = 85;
      static-blur = false;
    };
    "org/gnome/shell/extensions/blur-my-shell/screenshot" = {
      pipeline = "pipeline_default";
    };
    "org/gnome/shell/extensions/caffeine" = {
      cli-toggle = false;
      indicator-position-max = 1;
      user-enabled = true;
    };
    "org/gnome/shell/extensions/color-picker" = {
      auto-copy = true;
      color-picker-shortcut = [ "<Control><Super>c" ];
      enable-format = true;
      enable-notify = false;
      enable-shortcut = true;
      enable-sound = false;
      notify-sound = lib.hm.gvariant.mkUint32 1;
      notify-style = lib.hm.gvariant.mkUint32 0;
    };
    "org/gnome/shell/extensions/dash-in-panel" = {
      button-margin = 4;
      center-dash = true;
      colored-dot = false;
      dim-dot = false;
      icon-size = 32;
      move-date = true;
      panel-height = 46;
      show-apps = false;
      show-dash = false;
      show-label = false;
      show-running = false;
    };
    "org/gnome/shell/extensions/gsconnect" = {
      name = "erebor";
    };
    "org/gnome/shell/extensions/just-perfection" = {
      accent-color-icon = false;
      accessibility-menu = true;
      activities-button = false;
      background-menu = true;
      clock-menu = true;
      clock-menu-position = 1;
      clock-menu-position-offset = 20;
      controls-manager-spacing-size = 0;
      dash = true;
      dash-app-running = true;
      dash-separator = false;
      keyboard-layout = true;
      max-displayed-search-results = 0;
      panel-in-overview = true;
      panel-notification-icon = true;
      power-icon = false;
      quick-settings = true;
      quick-settings-dark-mode = true;
      ripple-box = true;
      show-apps-button = true;
      top-panel-position = 1;
      weather = true;
      window-picker-icon = true;
      window-preview-close-button = true;
      workspace = false;
      workspace-switcher-size = 0;
      workspaces-in-app-grid = true;
      world-clock = true;
    };
    "org/gnome/shell/extensions/pop-shell" = {
      tile-by-default = false;
    };
    "org/gnome/shell/extensions/user-theme" = {
      name = "Stylix";
    };
    "org/gnome/shell/extensions/vitals" = {
      alphabetize = true;
      fixed-widths = true;
      hide-icons = false;
      hide-zeros = true;
      icon-style = 1;
      include-static-gpu-info = true;
      include-static-info = true;
      menu-centered = false;
      position-in-panel = 2;
      show-fan = false;
      show-gpu = true;
      show-memory = true;
      show-network = true;
      show-processor = true;
      show-storage = true;
      show-system = true;
      show-temperature = true;
      show-voltage = false;
      use-higher-precision = false;
    };
    "org/gnome/shell/keybindings" = {
      toggle-overview = [ "<Super>" ];
    };
  };
}
