# Generated by dconf-nix
{ lib, ... }:

{
  dconf.settings = {
    "io/missioncenter/MissionCenter" = {
      apps-page-column-order = "";
      apps-page-show-column-separators = false;
      apps-page-sorting-column-name = "";
      apps-page-sorting-order = "Ascending";
      performance-selected-page = "cpu";
      window-height = 851;
      window-selected-page = "apps-page";
      window-width = 1126;
    };
    "org/gnome/Console" = {
      last-window-maximised = false;
      last-window-size = lib.hm.gvariant.mkTuple [ 812 576 ];
    };
    "org/gnome/Extensions" = {
      window-height = 1378;
      window-maximized = false;
      window-width = 850;
    };
    "org/gnome/TextEditor" = {
      style-scheme = "stylix";
    };
    "org/gnome/control-center" = {
      last-panel = "wifi";
      window-state = lib.hm.gvariant.mkTuple [ 980 640 false ];
    };
    "org/gnome/desktop/app-folders" = {
      folder-children = [ "System" "Utilities" "YaST" "Pardus" ];
    };
    "org/gnome/desktop/app-folders/folders/Pardus" = {
      categories = [ "X-Pardus-Apps" ];
      name = "X-Pardus-Apps.directory";
      translate = true;
    };
    "org/gnome/desktop/app-folders/folders/System" = {
      apps = [ "org.gnome.baobab.desktop" "org.gnome.DiskUtility.desktop" "org.gnome.Logs.desktop" "org.gnome.tweaks.desktop" ];
      name = "X-GNOME-Shell-System.directory";
      translate = true;
    };
    "org/gnome/desktop/app-folders/folders/Utilities" = {
      apps = [ "org.gnome.Decibels.desktop" "org.gnome.Connections.desktop" "org.gnome.Evince.desktop" "org.gnome.FileRoller.desktop" "org.gnome.font-viewer.desktop" "org.gnome.Loupe.desktop" "org.gnome.seahorse.Application.desktop" ];
      name = "X-GNOME-Shell-Utilities.directory";
      translate = true;
    };
    "org/gnome/desktop/app-folders/folders/YaST" = {
      categories = [ "X-SuSE-YaST" ];
      name = "suse-yast.directory";
      translate = true;
    };
    "org/gnome/desktop/background" = {
      color-shading-type = "solid";
      picture-options = "zoom";
      picture-uri = "file:///nix/store/iaa9q486iwr4r2vm09971ndb87pqxrsm-wallhaven-lym7pl.jpg";
      picture-uri-dark = "file:///nix/store/iaa9q486iwr4r2vm09971ndb87pqxrsm-wallhaven-lym7pl.jpg";
    };
    "org/gnome/desktop/input-sources" = {
      sources = [ "[xkb us]" "[xkb ru]" ];
      xkb-options = [ "terminate:ctrl_alt_bksp" ];
    };
    "org/gnome/desktop/interface" = {
      accent-color = "slate";
      color-scheme = "prefer-dark";
      document-font-name = "Inter  11";
      enable-animations = true;
      font-name = "Inter 12";
      gtk-theme = "adw-gtk3";
      monospace-font-name = "JetBrains Mono 12";
      toolkit-accessibility = false;
    };
    "org/gnome/desktop/notifications" = {
      application-children = [ "org-telegram-desktop" "firefox" ];
    };
    "org/gnome/desktop/notifications/application/firefox" = {
      application-id = "firefox.desktop";
    };
    "org/gnome/desktop/notifications/application/org-telegram-desktop" = {
      application-id = "org.telegram.desktop.desktop";
    };
    "org/gnome/desktop/wm/preferences" = {
      num-workspaces = 3;
    };
    "org/gnome/eog/view" = {
      background-color = "#1a1c1b";
    };
    "org/gnome/evolution-data-server" = {
      migrated = true;
    };
    "org/gnome/mutter" = {
      edge-tiling = true;
      experimental-features = [ "scale-monitor-framebuffer" ];
    };
    "org/gnome/nautilus/preferences" = {
      migrated-gtk-settings = true;
    };
    "org/gnome/shell" = {
      disable-user-extensions = false;
      disabled-extensions = [ "ding@rastersoft.com" ];
      enabled-extensions = [ "AlphabeticalAppGrid@stuarthayhurst" "appindicatorsupport@rgcjonas.gmail.com" "auto-accent-colour@Wartybix" "blur-my-shell@aunetx" "color-picker@tuberry" "dash-in-panel@fthx" "solaar-extension@sidevesh" "undecorate@sun.wxg@gmail.com" "user-theme@gnome-shell-extensions.gcampax.github.com" "Vitals@CoreCoding.com" "caffeine@patapon.info" "logomenu@aryan_k" "pop-shell@system76.com" "just-perfection-desktop@just-perfection" ];
      favorite-apps = [ "firefox.desktop" "org.gnome.Nautilus.desktop" "org.telegram.desktop.desktop" "org.gnome.Console.desktop" "code.desktop" ];
      last-selected-power-profile = "performance";
      welcome-dialog-last-shown-version = "48.4";
    };
    "org/gnome/shell/extensions/Logo-menu" = {
      hide-forcequit = true;
      hide-icon-shadow = false;
      hide-softwarecentre = true;
      menu-button-extensions-app = "org.gnome.Extensions.desktop";
      menu-button-icon-click-type = 2;
      menu-button-icon-image = 23;
      menu-button-icon-size = 24;
      menu-button-software-center = "";
      menu-button-system-monitor = "missioncenter";
      menu-button-terminal = "gnome-terminal";
      show-activities-button = false;
      show-lockscreen = true;
      show-power-options = true;
      symbolic-icon = true;
      use-custom-icon = false;
    };
    "org/gnome/shell/extensions/alphabetical-app-grid" = {
      folder-order-position = "start";
    };
    "org/gnome/shell/extensions/appindicator" = {
      icon-brightness = 0;
      icon-contrast = 0;
      icon-opacity = 240;
      icon-saturation = 0;
      icon-size = 0;
      legacy-tray-enabled = true;
      tray-pos = "right";
    };
    "org/gnome/shell/extensions/auto-accent-colour" = {
      disable-cache = false;
      hide-indicator = true;
      highlight-mode = true;
    };
    "org/gnome/shell/extensions/blur-my-shell" = {
      hacks-level = 1;
      settings-version = 2;
    };
    "org/gnome/shell/extensions/blur-my-shell/appfolder" = {
      brightness = 1;
      sigma = 85;
    };
    "org/gnome/shell/extensions/blur-my-shell/applications" = {
      blacklist = [ "Plank" "com.desktop.ding" "Conky" ".gamescope-wrapped" "steam_app_*" ".virt-manager-wrapped" ];
      blur = true;
      dynamic-opacity = false;
      enable-all = true;
      opacity = 230;
      sigma = 85;
    };
    "org/gnome/shell/extensions/blur-my-shell/coverflow-alt-tab" = {
      pipeline = "pipeline_default";
    };
    "org/gnome/shell/extensions/blur-my-shell/dash-to-dock" = {
      blur = false;
      brightness = 1;
      override-background = true;
      pipeline = "pipeline_default_rounded";
      sigma = 85;
      static-blur = false;
      style-dash-to-dock = 0;
      unblur-in-overview = true;
    };
    "org/gnome/shell/extensions/blur-my-shell/dash-to-panel" = {
      blur-original-panel = false;
    };
    "org/gnome/shell/extensions/blur-my-shell/hidetopbar" = {
      compatibility = false;
    };
    "org/gnome/shell/extensions/blur-my-shell/lockscreen" = {
      pipeline = "pipeline_default";
    };
    "org/gnome/shell/extensions/blur-my-shell/overview" = {
      pipeline = "pipeline_default";
    };
    "org/gnome/shell/extensions/blur-my-shell/panel" = {
      brightness = 1;
      override-background = true;
      pipeline = "pipeline_default";
      sigma = 85;
      static-blur = false;
    };
    "org/gnome/shell/extensions/blur-my-shell/screenshot" = {
      pipeline = "pipeline_default";
    };
    "org/gnome/shell/extensions/caffeine" = {
      indicator-position-max = 1;
    };
    "org/gnome/shell/extensions/color-picker" = {
      auto-copy = true;
      color-picker-shortcut = [ "<Control><Super>c" ];
      enable-format = true;
      enable-notify = false;
      enable-shortcut = true;
      enable-sound = false;
      notify-sound = lib.hm.gvariant.mkUint32 1;
      notify-style = lib.hm.gvariant.mkUint32 0;
    };
    "org/gnome/shell/extensions/dash-in-panel" = {
      button-margin = 6;
      center-dash = true;
      colored-dot = true;
      icon-size = 32;
      move-date = true;
      panel-height = 46;
      show-apps = false;
      show-dash = false;
      show-label = true;
    };
    "org/gnome/shell/extensions/just-perfection" = {
      accent-color-icon = false;
      accessibility-menu = true;
      activities-button = false;
      background-menu = true;
      clock-menu = true;
      clock-menu-position = 1;
      clock-menu-position-offset = 20;
      controls-manager-spacing-size = 0;
      dash = true;
      dash-app-running = true;
      dash-separator = false;
      keyboard-layout = true;
      max-displayed-search-results = 0;
      panel-in-overview = true;
      panel-notification-icon = true;
      power-icon = false;
      quick-settings = true;
      quick-settings-dark-mode = true;
      ripple-box = true;
      show-apps-button = false;
      support-notifier-showed-version = 34;
      support-notifier-type = 0;
      top-panel-position = 0;
      window-picker-icon = true;
      window-preview-close-button = true;
      workspace = false;
      workspace-switcher-size = 0;
      workspaces-in-app-grid = true;
      world-clock = true;
    };
    "org/gnome/shell/extensions/pop-shell" = {
      tile-by-default = false;
    };
    "org/gnome/shell/extensions/user-theme" = {
      name = "Stylix";
    };
    "org/gnome/shell/extensions/vitals" = {
      alphabetize = true;
      fixed-widths = true;
      hide-icons = false;
      hide-zeros = true;
      icon-style = 1;
      include-static-gpu-info = true;
      include-static-info = true;
      menu-centered = false;
      position-in-panel = 2;
      show-fan = false;
      show-gpu = true;
      show-memory = true;
      show-network = true;
      show-processor = true;
      show-storage = true;
      show-system = true;
      show-temperature = true;
      show-voltage = false;
      use-higher-precision = false;
    };
    "org/gnome/shell/keybindings" = {
      toggle-overview = [ "<Super>" ];
    };
    "org/gnome/shell/world-clocks" = {
      locations = [];
    };
    "org/gtk/gtk4/settings/file-chooser" = {
      show-hidden = false;
    };
    "org/gtk/settings/file-chooser" = {
      show-hidden = false;
    };
    "org/virt-manager/virt-manager/connections" = {
      autoconnect = [ "qemu:///system" ];
      uris = [ "qemu:///system" ];
    };
    "org/virt-manager/virt-manager/vmlist-fields" = {
      disk-usage = false;
      network-traffic = false;
    };  };
}
